// 1000 adjectives × 1000 nouns = 1,000,000 unique subdomain combos

export const ADJECTIVES = [
  'able', 'active', 'aero', 'agile', 'airy', 'alert', 'alive', 'alpha', 'amber', 'ample',
  'analog', 'anchor', 'angle', 'apex', 'aqua', 'arch', 'arctic', 'ardent', 'arid', 'ash',
  'aspen', 'astral', 'atomic', 'autumn', 'avid', 'awake', 'azure', 'basic', 'basin', 'bass',
  'beach', 'beam', 'benign', 'berry', 'birch', 'bird', 'bison', 'blaze', 'bliss', 'block',
  'bloom', 'blue', 'blush', 'board', 'bold', 'bone', 'bonus', 'boost', 'brave', 'bravo',
  'breeze', 'brick', 'bridge', 'brief', 'bright', 'brine', 'bronze', 'brook', 'buff', 'bunch',
  'buoyant', 'burnt', 'burst', 'cactus', 'calm', 'camel', 'candid', 'candy', 'canyon', 'cape',
  'carbon', 'cargo', 'cedar', 'celery', 'chalk', 'charm', 'chase', 'cherry', 'chess', 'chief',
  'chill', 'chrome', 'cider', 'circle', 'citrus', 'civic', 'clamp', 'clay', 'clean', 'clear',
  'clement', 'clever', 'cliff', 'climb', 'cloud', 'clover', 'coal', 'coast', 'cobra', 'cocoa',
  'coda', 'cogent', 'color', 'comet', 'cool', 'copper', 'coral', 'core', 'corn', 'cosmic',
  'cotton', 'couple', 'cozy', 'craft', 'crane', 'cream', 'creek', 'crest', 'crisp', 'cross',
  'crown', 'cruise', 'crush', 'crystal', 'cubic', 'curly', 'cyan', 'daisy', 'dapper', 'daring',
  'dark', 'dawn', 'decent', 'deep', 'delta', 'dense', 'desert', 'dew', 'direct', 'disco',
  'diver', 'dizzy', 'double', 'downy', 'dream', 'drift', 'drizzle', 'drum', 'dry', 'dual',
  'dulcet', 'dusk', 'dust', 'dynamic', 'eager', 'eagle', 'early', 'earth', 'east', 'easy',
  'ebony', 'echo', 'edge', 'eight', 'elastic', 'elite', 'elm', 'ember', 'emerald', 'empty',
  'energy', 'entire', 'entry', 'epic', 'equal', 'ergo', 'ethic', 'even', 'ever', 'exact',
  'extra', 'fabric', 'facet', 'faint', 'fair', 'falcon', 'fall', 'fancy', 'fast', 'feather',
  'fern', 'fervent', 'fervid', 'fiber', 'field', 'fierce', 'fig', 'final', 'fine', 'fire',
  'firm', 'first', 'fizz', 'flake', 'flame', 'flannel', 'flare', 'flash', 'flat', 'fleet',
  'flex', 'flint', 'float', 'flock', 'flora', 'floral', 'florid', 'flow', 'fluff', 'fluid',
  'flush', 'foam', 'focal', 'fog', 'foggy', 'folk', 'forest', 'forge', 'form', 'forte',
  'fossil', 'fox', 'frame', 'free', 'fresh', 'frost', 'frosty', 'frozen', 'fruit', 'full',
  'funky', 'fury', 'fuse', 'fusion', 'fuzzy', 'gale', 'gallant', 'gambit', 'garden', 'garnet',
  'gauge', 'gemini', 'gentle', 'ghost', 'giant', 'gifted', 'ginger', 'glacial', 'glad', 'glade',
  'glass', 'gleam', 'glide', 'global', 'glossy', 'glow', 'gold', 'golden', 'gorge', 'grace',
  'grain', 'grand', 'grape', 'gravel', 'gray', 'great', 'green', 'grey', 'grit', 'groovy',
  'ground', 'grove', 'guild', 'guitar', 'gust', 'habit', 'happy', 'harbor', 'hardy', 'haven',
  'hawk', 'haze', 'hazel', 'heap', 'heart', 'heavy', 'hedge', 'hemp', 'hero', 'heron',
  'hex', 'hidden', 'high', 'hill', 'hive', 'hollow', 'home', 'honest', 'honey', 'hoop',
  'hope', 'horn', 'hot', 'hover', 'hue', 'huge', 'human', 'humble', 'hustle', 'hydro',
  'hyper', 'ice', 'icy', 'idle', 'igloo', 'import', 'inch', 'index', 'indie', 'indigo',
  'ink', 'inner', 'input', 'ion', 'iron', 'island', 'isle', 'ivory', 'ivy', 'jade',
  'jasmine', 'jasper', 'java', 'jazzy', 'jelly', 'jet', 'jewel', 'jeweled', 'jolly', 'jolt',
  'journal', 'jovial', 'joy', 'juice', 'jumbo', 'jungle', 'junior', 'just', 'kale', 'karma',
  'kayak', 'keen', 'kernel', 'kettle', 'khaki', 'kind', 'kindle', 'kinetic', 'kite', 'knack',
  'knit', 'kraft', 'kudos', 'lace', 'lagoon', 'lake', 'lamp', 'lance', 'lapis', 'large',
  'laser', 'latch', 'latent', 'later', 'latte', 'lava', 'lavish', 'lawn', 'layer', 'leaf',
  'lean', 'legend', 'lemon', 'lens', 'lesser', 'level', 'lever', 'lichen', 'lifted', 'light',
  'lilac', 'lily', 'lime', 'linden', 'linen', 'lion', 'liquid', 'lit', 'litmus', 'little',
  'live', 'lively', 'llama', 'local', 'lodge', 'loft', 'logic', 'lone', 'long', 'loop',
  'lotus', 'loud', 'lucent', 'lucid', 'lucky', 'lumber', 'lumen', 'lunar', 'lush', 'luxe',
  'lyric', 'magic', 'major', 'mango', 'manor', 'maple', 'marble', 'margin', 'marin', 'market',
  'marsh', 'mason', 'master', 'matte', 'max', 'meadow', 'median', 'mega', 'mellow', 'melon',
  'memory', 'merit', 'merry', 'mesa', 'metal', 'metro', 'micro', 'mighty', 'mild', 'mill',
  'mineral', 'mini', 'mint', 'mirror', 'mist', 'misty', 'mobile', 'mocha', 'modern', 'modest',
  'molten', 'moment', 'mono', 'moon', 'morph', 'moss', 'mossy', 'motion', 'motor', 'mount',
  'multi', 'muon', 'mural', 'muscle', 'muse', 'muted', 'mystic', 'myth', 'nano', 'narrow',
  'nascent', 'native', 'nature', 'naval', 'navy', 'neat', 'nebula', 'nectar', 'neon', 'nerve',
  'nested', 'nettle', 'neural', 'new', 'next', 'nice', 'night', 'nimble', 'nimbus', 'ninth',
  'nitro', 'noble', 'nomad', 'normal', 'north', 'notch', 'nova', 'novel', 'null', 'nutmeg',
  'nylon', 'oak', 'oasis', 'ocean', 'ochre', 'odd', 'offset', 'olive', 'omega', 'onyx',
  'opal', 'open', 'optic', 'orange', 'orbit', 'orchid', 'origin', 'osprey', 'other', 'otter',
  'outer', 'oval', 'owl', 'oxide', 'oyster', 'pale', 'palm', 'panda', 'panel', 'paper',
  'park', 'parrot', 'pastel', 'patch', 'path', 'pause', 'paver', 'peace', 'peach', 'peak',
  'pearl', 'pebble', 'pecan', 'penny', 'pepper', 'perch', 'perk', 'petal', 'photo', 'piano',
  'pier', 'pilot', 'pine', 'pink', 'pivot', 'pixel', 'placid', 'planar', 'planet', 'plant',
  'plate', 'plaza', 'pliant', 'plucky', 'plum', 'plush', 'pocket', 'poem', 'point', 'polar',
  'polite', 'pond', 'poplar', 'poppy', 'port', 'portal', 'poster', 'potent', 'power', 'presto',
  'primal', 'prime', 'print', 'prism', 'proton', 'proud', 'proxy', 'puddle', 'pulse', 'pumice',
  'pure', 'quartz', 'quest', 'quick', 'quiet', 'quill', 'quirky', 'quota', 'rabbit', 'radial',
  'radish', 'raft', 'rain', 'rally', 'range', 'rapid', 'rare', 'ratio', 'raven', 'raw',
  'reach', 'ready', 'real', 'record', 'red', 'reef', 'regal', 'relay', 'remote', 'renew',
  'resin', 'rhythm', 'ribbon', 'rich', 'ridge', 'ripe', 'ripple', 'risen', 'river', 'robin',
  'robust', 'rock', 'rocket', 'roman', 'root', 'rope', 'rosy', 'rough', 'round', 'rover',
  'royal', 'ruby', 'rumble', 'runner', 'rush', 'russet', 'rustic', 'sable', 'saddle', 'safari',
  'safe', 'sage', 'salmon', 'salt', 'sand', 'sandy', 'satin', 'savvy', 'scarlet', 'scenic',
  'scope', 'scout', 'sea', 'seed', 'select', 'senior', 'sensor', 'sepia', 'serene', 'serif',
  'settle', 'seven', 'shade', 'shadow', 'shale', 'sharp', 'shelf', 'shell', 'shield', 'shift',
  'shiny', 'shoal', 'shore', 'short', 'shrub', 'sierra', 'sigma', 'signal', 'silk', 'silo',
  'silver', 'simple', 'single', 'sixth', 'sketch', 'skill', 'sky', 'slate', 'sleek', 'sleet',
  'slice', 'slick', 'slim', 'slope', 'small', 'smart', 'smoke', 'smooth', 'snap', 'snappy',
  'snow', 'snowy', 'snug', 'social', 'socket', 'soda', 'soft', 'solar', 'solid', 'sonar',
  'sonic', 'sorbet', 'sound', 'south', 'space', 'spade', 'span', 'spark', 'sparse', 'speed',
  'sphere', 'spice', 'spin', 'spiral', 'splash', 'spoke', 'sponge', 'spring', 'sprout', 'spruce',
  'spun', 'square', 'stable', 'stanza', 'staple', 'star', 'stark', 'static', 'steady', 'steam',
  'steel', 'steep', 'stem', 'stereo', 'still', 'stir', 'stitch', 'stock', 'stoic', 'stoked',
  'stone', 'storm', 'story', 'stout', 'strata', 'stream', 'stripe', 'strong', 'strum', 'strut',
  'studio', 'sturdy', 'style', 'suave', 'subtle', 'sugar', 'summit', 'sun', 'sunny', 'super',
  'supple', 'supra', 'sure', 'surf', 'surge', 'swan', 'sweet', 'swift', 'swirl', 'syrup',
  'table', 'tall', 'talon', 'tandem', 'tango', 'tartan', 'tawny', 'teal', 'tempo', 'tender',
  'tenth', 'terra', 'theta', 'thick', 'thin', 'third', 'thorn', 'thrift', 'thrive', 'tidal',
  'tide', 'tiger', 'timber', 'tiny', 'titan', 'toast', 'token', 'topaz', 'torch', 'total',
  'tower', 'trace', 'trail', 'trance', 'treble', 'trend', 'triad', 'tribal', 'triple', 'trophy',
  'tropic', 'trout', 'true', 'trunk', 'trust', 'tulip', 'turbo', 'turf', 'tuscan', 'twin',
  'twist', 'ultra', 'umbra', 'union', 'unique', 'unity', 'upbeat', 'upland', 'upper', 'urban',
  'utmost', 'valid', 'valley', 'valor', 'valve', 'vapor', 'vast', 'vault', 'velvet', 'venus',
  'verdant', 'verge', 'verse', 'vessel', 'vibes', 'vigor', 'vine', 'viola', 'violet', 'viper',
  'vision', 'visual', 'vital', 'vivid', 'vocal', 'vogue', 'volt', 'vortex', 'wafer', 'walnut',
  'warm', 'wasabi', 'watch', 'water', 'wave', 'wax', 'weave', 'wedge', 'west', 'wheat',
  'whirl', 'white', 'whole', 'wide', 'wild', 'willow', 'wind', 'wing', 'winter', 'wire',
  'wise', 'wispy', 'wizard', 'wolf', 'wonder', 'wooden', 'wool', 'worthy', 'woven', 'xenon',
  'yacht', 'yarn', 'yellow', 'yield', 'young', 'zen', 'zenith', 'zephyr', 'zero', 'zesty',
  'zigzag', 'zinc', 'zodiac', 'zonal', 'zone', 'zoom', 'zulu',
  'crimson', 'sienna', 'taupe', 'pewter', 'mauve', 'cerulean', 'umber',
  'maroon', 'magenta', 'plaid', 'striped', 'silky', 'grainy', 'gritty',
  'velvety', 'pearly', 'chalky', 'waxy', 'dewy', 'spongy', 'porous',
  'coarse', 'wiry', 'somber', 'drowsy', 'peppy', 'chipper', 'dreamy',
  'heady', 'blithe', 'bubbly', 'wistful', 'perky', 'giddy', 'spunky',
  'brisk', 'lanky', 'stocky', 'petite', 'terse', 'hasty', 'zippy',
  'tepid', 'muggy', 'balmy', 'sultry', 'frigid', 'torrid', 'boreal',
  'opaque', 'sheer', 'radiant', 'dusky',
]

export const NOUNS = [
  'falcon', 'hawk', 'eagle', 'raven', 'wren', 'finch', 'robin', 'crane', 'heron', 'osprey',
  'condor', 'swift', 'lark', 'dove', 'jay', 'owl', 'fox', 'wolf', 'lynx', 'otter',
  'bison', 'moose', 'elk', 'stag', 'mare', 'colt', 'ram', 'bull', 'bear', 'lion',
  'tiger', 'puma', 'cobra', 'viper', 'drake', 'salmon', 'trout', 'bass', 'pike', 'cod',
  'squid', 'seal', 'whale', 'shark', 'moth', 'wasp', 'beetle', 'mantis', 'hornet', 'jackal',
  'badger', 'marten', 'ferret', 'mink', 'stoat', 'hound', 'husky', 'collie', 'boxer', 'ibex',
  'yak', 'gnu', 'oryx', 'kudu', 'eland', 'panda', 'koala', 'lemur', 'gecko', 'newt',
  'toad', 'frog', 'crab', 'clam', 'shrimp', 'eel', 'koi', 'perch', 'walrus', 'narwhal',
  'orca', 'pelican', 'parrot', 'macaw', 'toucan', 'egret', 'stork', 'kestrel', 'merlin', 'grouse',
  'quail', 'plover', 'tern', 'gull', 'murre', 'puffin', 'bobcat', 'ocelot', 'cheetah', 'panther',
  'jaguar', 'mustang', 'bronco', 'sparrow', 'bunting', 'thrush', 'oriole', 'magpie', 'rook', 'jackdaw',
  'martin', 'shrike', 'pipit', 'cedar', 'birch', 'aspen', 'maple', 'willow', 'spruce', 'pine',
  'oak', 'elm', 'larch', 'alder', 'yew', 'ash', 'teak', 'balsa', 'beech', 'holly',
  'ivy', 'fern', 'moss', 'sage', 'basil', 'thyme', 'clover', 'lotus', 'lily', 'tulip',
  'orchid', 'daisy', 'poppy', 'aster', 'iris', 'peony', 'dahlia', 'violet', 'jasmine', 'acacia',
  'myrtle', 'laurel', 'olive', 'palm', 'bamboo', 'reed', 'vine', 'root', 'bark', 'leaf',
  'thorn', 'bloom', 'bud', 'grove', 'copse', 'glade', 'dell', 'glen', 'dale', 'marsh',
  'moor', 'heath', 'fen', 'meadow', 'prairie', 'steppe', 'savanna', 'taiga', 'canopy', 'hedge',
  'bramble', 'nettle', 'sorrel', 'clove', 'saffron', 'aloe', 'flax', 'hemp', 'rye', 'oat',
  'malt', 'berry', 'plum', 'peach', 'quince', 'lemon', 'lime', 'fig', 'date', 'gourd',
  'melon', 'mango', 'guava', 'acorn', 'lichen', 'kelp', 'spore', 'petal', 'stem', 'frond',
  'nova', 'comet', 'orbit', 'quasar', 'nebula', 'pulsar', 'zenith', 'cosmos', 'lunar', 'solar',
  'photon', 'proton', 'neutron', 'ion', 'plasma', 'aurora', 'corona', 'meteor', 'prism', 'flare',
  'halo', 'nimbus', 'cirrus', 'stratus', 'cumulus', 'vortex', 'gale', 'zephyr', 'breeze', 'squall',
  'tempest', 'thunder', 'frost', 'sleet', 'hail', 'mist', 'fog', 'dew', 'rime', 'glint',
  'gleam', 'glare', 'glow', 'beam', 'spark', 'flash', 'dawn', 'dusk', 'eclipse', 'horizon',
  'orion', 'sirius', 'vega', 'rigel', 'polaris', 'ridge', 'cliff', 'peak', 'summit', 'crest',
  'mesa', 'butte', 'bluff', 'ledge', 'shelf', 'gorge', 'canyon', 'ravine', 'valley', 'basin',
  'delta', 'fjord', 'inlet', 'cove', 'bay', 'cape', 'isle', 'atoll', 'lagoon', 'reef',
  'shoal', 'dune', 'shore', 'beach', 'coast', 'tundra', 'glacier', 'icecap', 'moraine', 'plateau',
  'terrace', 'knoll', 'mound', 'tor', 'spire', 'arch', 'pillar', 'column', 'bridge', 'ford',
  'pass', 'trail', 'path', 'route', 'divide', 'oasis', 'spring', 'brook', 'creek', 'stream',
  'rapids', 'falls', 'pool', 'pond', 'lake', 'harbor', 'wharf', 'jetty', 'pier', 'dock',
  'port', 'haven', 'strait', 'channel', 'narrows', 'crater', 'caldera', 'geyser', 'vent', 'flume',
  'chute', 'sluice', 'weir', 'dam', 'levee', 'stone', 'flint', 'slate', 'basalt', 'granite',
  'marble', 'quartz', 'onyx', 'opal', 'jade', 'agate', 'garnet', 'topaz', 'amber', 'pearl',
  'ruby', 'cobalt', 'nickel', 'copper', 'bronze', 'brass', 'steel', 'iron', 'zinc', 'chrome',
  'carbon', 'silicon', 'neon', 'xenon', 'argon', 'helium', 'lithium', 'radium', 'mercury', 'silver',
  'gold', 'tin', 'lead', 'tungsten', 'alloy', 'ingot', 'ore', 'slag', 'oxide', 'solder',
  'enamel', 'lacquer', 'resin', 'glass', 'crystal', 'gem', 'shard', 'facet', 'prong', 'rivet',
  'bolt', 'nail', 'wire', 'cable', 'fiber', 'silk', 'linen', 'cotton', 'tweed', 'denim',
  'suede', 'felt', 'velvet', 'satin', 'pixel', 'node', 'vector', 'vertex', 'voxel', 'nexus',
  'matrix', 'cipher', 'codec', 'modem', 'servo', 'rotor', 'piston', 'valve', 'lever', 'pulley',
  'gear', 'crank', 'axle', 'cam', 'beacon', 'signal', 'pulse', 'relay', 'switch', 'diode',
  'laser', 'radar', 'sonar', 'lidar', 'drone', 'probe', 'rover', 'shuttle', 'capsule', 'module',
  'panel', 'array', 'grid', 'mesh', 'lens', 'scope', 'gauge', 'dial', 'meter', 'sensor',
  'anchor', 'socket', 'hub', 'kernel', 'stack', 'cache', 'queue', 'buffer', 'token', 'hash',
  'block', 'chain', 'forge', 'anvil', 'lathe', 'drill', 'clamp', 'vise', 'chisel', 'blade',
  'edge', 'point', 'helm', 'shield', 'arrow', 'lance', 'sword', 'mace', 'spear', 'axe',
  'bow', 'dart', 'torch', 'lamp', 'candle', 'lantern', 'mirror', 'bell', 'horn', 'drum',
  'flute', 'lyre', 'harp', 'gong', 'chime', 'cymbal', 'pipe', 'fife', 'flag', 'banner',
  'badge', 'coin', 'medal', 'crown', 'ring', 'vault', 'chest', 'crate', 'barrel', 'flask',
  'vial', 'cup', 'bowl', 'plate', 'dish', 'keel', 'mast', 'hull', 'rudder', 'sail',
  'oar', 'plank', 'timber', 'rafter', 'brick', 'tile', 'slab', 'frame', 'strut', 'brace',
  'truss', 'dome', 'cloak', 'vest', 'sash', 'belt', 'clasp', 'buckle', 'latch', 'hinge',
  'knob', 'storm', 'gust', 'blast', 'surge', 'swell', 'drift', 'flow', 'flux', 'tide',
  'current', 'ripple', 'eddy', 'wake', 'spray', 'foam', 'surf', 'wave', 'billow', 'roller',
  'tremor', 'quake', 'rumble', 'boom', 'crack', 'snap', 'whip', 'lash', 'thrust', 'impact',
  'force', 'torque', 'inertia', 'kinetic', 'charge', 'field', 'aura', 'spirit', 'vigor', 'verve',
  'grit', 'nerve', 'mettle', 'valor', 'honor', 'merit', 'virtue', 'quest', 'voyage', 'venture',
  'gambit', 'wager', 'stake', 'claim', 'title', 'creed', 'maxim', 'motto', 'axiom', 'canon',
  'tenet', 'ethic', 'code', 'logic', 'reason', 'method', 'craft', 'skill', 'knack', 'flair',
  'talent', 'prowess', 'forte', 'asset', 'trait', 'mark', 'rank', 'grade', 'tier', 'notch',
  'phase', 'stage', 'epoch', 'era', 'cycle', 'span', 'range', 'depth', 'reach', 'grasp',
  'grip', 'hold', 'stance', 'poise', 'grace', 'pace', 'stride', 'tempo', 'rhythm', 'cadence',
  'beat', 'pitch', 'tone', 'timbre', 'chord', 'note', 'key', 'scale', 'octave', 'verse',
  'stanza', 'lyric', 'ballad', 'riff', 'motif', 'raptor', 'sentry', 'outpost', 'bastion', 'citadel',
  'rampart', 'turret', 'bunker', 'keep', 'dynamo', 'turbine', 'reactor', 'furnace', 'kiln', 'crucible',
  'foundry', 'smithy', 'depot', 'atlas', 'compass', 'sextant', 'sundial', 'pendulum', 'gyro', 'optic',
  'lumen', 'watt', 'joule', 'tesla', 'hertz', 'kelvin', 'pascal', 'newton', 'gauss', 'alpha',
  'sigma', 'theta', 'omega', 'kappa', 'gamma', 'lambda', 'zeta', 'phi', 'pinnacle', 'apex',
  'acme', 'nadir', 'origin', 'source', 'font', 'echo', 'phantom', 'wraith', 'specter', 'shade',
  'ghost', 'mirage', 'vision', 'enigma', 'riddle', 'puzzle', 'rune', 'glyph', 'sigil', 'emblem',
  'icon', 'totem', 'strider', 'flicker', 'cobble', 'sandstone', 'limestone', 'ironwood', 'lodestone', 'keystone',
  'capstone', 'sunstone', 'moonstone', 'cascade', 'facade', 'monsoon', 'typhoon', 'cyclone', 'tornado', 'blizzard',
  'tsunami', 'inferno', 'bellows', 'tongs', 'hammer', 'mallet', 'wedge', 'awl', 'rasp', 'mortar',
  'pestle', 'beaker', 'filter', 'shutter', 'obsidian', 'magma', 'pumice', 'silt', 'clay', 'chalk',
  'mica', 'cavern', 'hollow', 'burrow', 'warren', 'den', 'lair', 'roost', 'thicket', 'orchard',
  'arbor', 'trellis', 'pouch', 'satchel', 'quiver', 'sheath', 'holster', 'bracket', 'gasket', 'washer',
  'nozzle', 'funnel', 'spout', 'conduit', 'bollard', 'plinth', 'pedestal', 'podium', 'scaffold', 'skyline',
  'grotto', 'alcove', 'chapel', 'shrine', 'temple', 'pagoda', 'obelisk', 'monolith', 'pyramid', 'hangar',
  'runway', 'tarmac', 'gravel', 'curb', 'paver', 'caliper', 'transit', 'level', 'plumb', 'square',
  'ruler', 'retort', 'pipette', 'cinder', 'smelter', 'loam', 'shale', 'chert', 'zircon', 'spinel',
  'peridot', 'sapphire', 'emerald', 'diamond', 'platinum', 'iridium', 'prowler', 'tracker', 'ranger', 'scout',
  'warden', 'sentinel', 'marshal', 'frigate', 'corvette', 'galleon', 'clipper', 'schooner', 'kayak', 'canoe',
  'gondola', 'sloop', 'ketch', 'nacelle', 'manifold', 'header', 'flange', 'parcel', 'packet', 'bundle',
  'gangway', 'catwalk', 'dais', 'artifact', 'relic', 'fossil', 'remnant', 'lookout', 'landmark', 'hallmark',
  'turbo', 'throttle', 'circuit', 'magnet', 'monarch', 'gallop', 'canter', 'cannon', 'paragon', 'furrow',
  'berm', 'swale', 'gulch', 'arroyo',
  'iguana', 'marmot', 'wombat', 'possum', 'sloth', 'tapir', 'ermine',
  'dingo', 'hyena', 'coyote', 'mastiff', 'beagle', 'spaniel', 'minnow',
  'mullet', 'marlin', 'tuna', 'bonito', 'grouper', 'anchovy', 'starling',
  'cicada', 'locust', 'weevil', 'mantid', 'parsec', 'quark', 'boson',
  'gluon', 'hadron', 'lepton', 'tachyon', 'widget', 'gadget', 'ratchet',
  'flywheel', 'filament', 'cathode', 'anode', 'downpour', 'rainbow', 'icicle',
  'snowcap', 'isthmus', 'outcrop', 'quarry', 'escarp', 'bauxite', 'feldspar',
  'pyrite', 'galena', 'gneiss', 'schist', 'goblet', 'flagon', 'cauldron',
  'scalpel', 'inkwell', 'thimble', 'bobbin', 'spindle', 'trowel', 'pliers',
  'wrench', 'rigging', 'capstan', 'windlass', 'hawser', 'bowsprit', 'mulch',
  'humus', 'sapling', 'seedling', 'pinecone', 'estuary', 'sandbar', 'tideway',
  'seabed', 'bedrock', 'cogwheel', 'sprocket', 'ballast', 'bulkhead', 'porthole',
  'parapet', 'almanac', 'codex', 'tablet', 'scroll', 'ledger', 'gazette',
  'pamphlet', 'inkblot', 'canvas', 'easel', 'palette', 'pigment', 'patina',
  'veneer', 'tripod', 'belljar', 'retina', 'cornea', 'synapse', 'cortex',
  'tendon', 'cocoon', 'chrysalis', 'geode', 'cairn', 'steeple', 'dormer',
  'cupola', 'minaret', 'gimbal', 'belfry',
]
